# Generated by Django 3.0.8 on 2020-08-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riders',
            name='created',
        ),
        migrations.RemoveField(
            model_name='riders',
            name='last_modified',
        ),
    ]
