# Generated by Django 3.0.8 on 2020-08-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200814_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='agegroup',
        ),
    ]
