# Generated by Django 3.0.8 on 2020-08-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_web_agegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='state',
        ),
        migrations.RemoveField(
            model_name='web',
            name='team_member1',
        ),
        migrations.RemoveField(
            model_name='web',
            name='team_member2',
        ),
        migrations.RemoveField(
            model_name='web',
            name='team_member3',
        ),
        migrations.RemoveField(
            model_name='web',
            name='team_member4',
        ),
        migrations.RemoveField(
            model_name='web',
            name='team_option',
        ),
        migrations.RemoveField(
            model_name='web',
            name='velodrome',
        ),
    ]
