# Generated by Django 3.0.8 on 2020-08-14 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0007_auto_20200814_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='riders',
            new_name='rider',
        ),
    ]
