# Generated by Django 3.0.8 on 2020-08-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200814_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='ip_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tp_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ts_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tt200_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
