# Generated by Django 3.0.8 on 2020-08-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200814_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='ip_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tp_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ts_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tt200_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
