# Generated by Django 3.0.8 on 2020-08-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200815_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='velodrome',
            field=models.CharField(choices=[('Dunc Gray Velodrome', 'Dunc Gray Velodrome'), ('NT Velodrome', 'NT Velodrome'), ('Anna Meares Velodrome', 'Anna Meares Velodrome'), ('Super-Dome', 'Super-Dome'), ('Silverdome', 'Silverdome'), ('DISC', 'DISC'), ('Speed Dome', 'Speed Dome')], default='Dunc Gray Velodrome', max_length=50),
        ),
    ]
