# Generated by Django 3.0.8 on 2020-08-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200816_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='id',
        ),
        migrations.AddField(
            model_name='rider',
            name='number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
