# Generated by Django 3.0.8 on 2020-09-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200817_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='ip_humdity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='ip_time_second',
            field=models.FloatField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tp_humdity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tp_time_second',
            field=models.FloatField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='ts_humdity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt200_humdity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ip_time',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ts_time',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tt200_time',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
