# Generated by Django 3.0.8 on 2020-09-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200910_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='ip_time_total',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tp_time_total',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
    ]
