# Generated by Django 3.0.8 on 2020-09-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200910_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='ip_time',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ip_time_second',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tp_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
