# Generated by Django 3.0.8 on 2020-09-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200910_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='tp_time_second',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
