# Generated by Django 3.0.8 on 2020-09-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200910_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='tt_adjusted_second',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt_adjusted_time',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt_bp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt_humdity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt_time',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt_time_second',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt_time_total',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='tt_time_total_adjusted',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='agegroup',
            field=models.CharField(choices=[('JM15', 'JM15'), ('JW15', 'JW15'), ('JM17', 'JM17'), ('JW17', 'JW17'), ('JM19', 'JM19'), ('JW19', 'JW19'), ('ELITEM', 'ELITEM'), ('ELITEW', 'ELITEW'), ('Para-B', 'PARA-B'), ('Para-C', 'PARA-C')], default='JM15', max_length=6),
        ),
    ]
