# Generated by Django 3.0.8 on 2020-10-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200911_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='tp_ineligable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='ts_ineligable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ip_adjusted_second',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ip_adjusted_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tp_adjusted_second',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tp_adjusted_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tt_adjusted_second',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='tt_adjusted_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
