# Generated by Django 3.0.8 on 2020-11-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20201110_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='idnumber',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='number',
            field=models.IntegerField(),
        ),
    ]
