# Generated by Django 3.0.8 on 2020-11-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20201110_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_option',
            field=models.CharField(choices=[('Nat', 'National'), ('NJTS', 'NJTS')], default='Nat', max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
