# Generated by Django 3.0.8 on 2020-11-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20201110_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='rider',
            name='idnumber',
        ),
        migrations.AddField(
            model_name='rider',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
