# Generated by Django 3.0.8 on 2020-11-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20201111_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['-event', '-id']},
        ),
        migrations.AddField(
            model_name='event',
            name='finish',
            field=models.DateField(null=True),
        ),
    ]
