# Generated by Django 3.0.8 on 2020-11-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='team_option',
            new_name='event_option',
        ),
        migrations.AlterField(
            model_name='rider',
            name='event',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Event'),
        ),
    ]
