# Generated by Django 3.1.1 on 2020-11-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20201114_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='representing',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
